#spring:
#  redis:
#    host: 10.16.110.63
#      port: 6379
#      password: 123456
#      database: 0 # dev环境下用0号数据库
#      lettuce:
#        pool:
#          max-idle: 16
#          max-active: 32
#          min-idle: 8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minigo?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
