#spring:
#  redis:
#    host: 10.16.110.63
#      port: 6379
#      password: 123456
#      database: 0 # dev环境下用0号数据库
#      lettuce:
#        pool:
#          max-idle: 16
#          max-active: 32
#          min-idle: 8